bookstore/books/urls.py
from django.conf.urls import url
from . import views

app_name = 'books'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^books/$', views.BookIndexView.as_view(), name='books_index'),
    url(r'^writer/(?P<pk>[0-9]+)/$', views.WriterDetailView.as_view(), name='writer_detail'),
    url(r'^writer/add/$', views.WriterCreate.as_view(), name='writer-add'),
    url(r'^writer/update/(?P<pk>[0-9]+)/$', views.WriterUpdate.as_view(), name='writer-update'),
    url(r'^writer/(?P<pk>[0-9]+)/delete/$', views.WriterDelete.as_view(), name='writer-delete'),
    url(r'^book/(?P<pk>[0-9]+)/$', views.BookDetailView.as_view(), name='book_detail'),
    url(r'^book/add/$', views.BookCreate.as_view(), name='book-add'),
    url(r'^book/update/(?P<pk>[0-9]+)/$', views.BookUpdate.as_view(), name='book-update'),
    url(r'^book/(?P<pk>[0-9]+)/delete/$', views.BookDelete.as_view(), name='book-delete'),
]

bookstore/bookstore/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'books/', include('books.urls')),
]

bookstore/books/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Writer(models.Model):
    name = models.CharField(max_length=50)
    genre = models.CharField(max_length=20)
    nationality = models.CharField(max_length=50)
    writer_photo = models.CharField(max_length=300)

    def get_absolute_url(self):
        return reverse('books:writer_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name + " - " + self.nationality

class Book(models.Model):
    book_title = models.CharField(max_length=40)
    writer = models.ForeignKey(Writer, on_delete=models.CASCADE)
    book_cover = models.CharField(max_length=300)
    genre = models.CharField(max_length=20)
    series = models.CharField(max_length=50)

    def get_absolute_url(self):
        return reverse('books:book_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.book_title

bookstore/books/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import Writer, Book

class IndexView(generic.ListView):
    template_name = 'books/index.html'
    context_object_name = "all_writers"

    def get_queryset(self):
        return Writer.objects.all()

class WriterDetailView(generic.DetailView):
    model = Writer
    template_name = 'books/writer_detail.html'

    def get_queryset(self):
        return Writer.objects.all()

class BookIndexView(generic.ListView):
    template_name = 'books/book_index.html'
    context_object_name = "all_books"

    def get_queryset(self):
        return Book.objects.all()

class BookDetailView(generic.DetailView):
    model = Book
    template_name = 'books/book_detail.html'

    def get_queryset(self):
        return Book.objects.all()

class WriterCreate(CreateView):
    model = Writer
    fields = ['name', 'genre', 'nationality', 'writer_photo']

class WriterUpdate(UpdateView):
    model = Writer
    fields = ['name', 'genre', 'nationality', 'writer_photo']

class WriterDelete(DeleteView):
    model = Writer
    success_url = reverse_lazy('books:index')

class BookCreate(CreateView):
    model = Book
    fields = ['book_title', 'writer', 'book_cover', 'genre', 'series']

class BookUpdate(UpdateView):
    model = Book
    fields = ['book_title', 'writer', 'book_cover', 'genre', 'series']

class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('books:books_index')

bookstore/books/templates/books/base.html
<!DOCTYPE html>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'books/style.css' %}" />
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>{% block title %} Bookstore {% endblock %}
    </title>

</head>
    <body>
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'books:index' %}">Bookstore</a>
                </div>

                <!--Items-->
                <div class="collapse navbar-collapse" id="topNavBar">
                    <ul class="nav navbar-nav">
                        <li class="{% block writer_active %} {% endblock %}">
                            <a href="{% url 'books:index' %}">
                                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Writers
                            </a>
                        </li>
                        <li class="{% block book_active %} {% endblock %}">
                            <a href="{% url 'books:books_index' %}">
                                <span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp; Books
                            </a>
                        </li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li class="">
                            {% block addition_type %}
                            <a href="{% url 'books:writer-add' %}">
                                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Writer
                            </a>
                            {% endblock %}
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block body %}
        {% endblock %}
    </body>
</html>

bookstore/books/templates/books/book_detail.html
{% extends 'books/base.html' %}
{% block title %}Book Details{% endblock %}
{% block body %}
<img src="{{ book.book_cover }}" style="width: 150px; height: 200px;">

<h1>Title: {{book.book_title}}</h1><h2>Genre: {{ book.genre }}</h2>
<h3>Series: {{book.series}}</h3>
{{book.writer}}
{% endblock %}

bookstore/books/templates/books/book_form.html
{% extends 'books/base.html' %}
{% block title %}Add a New Book{% endblock %}
{% block book_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'books/form_template.html' %}
                        <div class="form-group">

                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

bookstore/books/templates/books/book_index.html
{% extends 'books/base.html' %}
{% block book_active %}active{% endblock %}
{% block body %}

        <ul>
            {% for book in all_books %}
            <li>
            <div class="caption">
                <a href="{% url 'books:book_detail' book.id %}">
                <img src="{{ book.book_cover }}" style="width: 150px; height: 200px;">
                </a>
                <h2>{{ book.book_title }}</h2>
                <h4>{{ book.writer }}</h4>
                <a href="{% url 'books:book_detail' book.id %}" class="btn btn-primary btn-sm"> View Details</a>
    <!--delete -->
                <form action="{% url 'books:book-delete' book.id %}" method="post" style="display: inline;">
                    {% csrf_token %}
                    <input type="hidden" name="writer_id" value="{{ writer.id }}"/>
                    <button type="submit" class="btn btn-default btn-sm">
                        <span class="glyphicon glyphicon-trash"></span>
                    </button>
                </form>

                <a href="{% url 'books:book-update' book.id %}" class="btn btn-default btn-sm">
                        <span class="glyphicon glyphicon-edit"></span>
                </a>

                <a href="#" class="btn btn-default btn-sm btn-favorite">
                    <span class="glyphicon glyphicon-star {% if writer.is_favorite %}active{% endif %}"></span>
                </a>
            </div>
            </li>
            {% endfor %}
        </ul>

{% endblock %}
{% block addition_type %}
<a href="{% url 'books:book-add' %}">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Book
</a>
{% endblock %}

bookstore/books/templates/books/create_book.html
{% extends 'books/base.html' %}
{% block title %}Add a New Book{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                        <a href="{% url 'books:writer_detail' writer.id %}">
                            {% if writer.writer_photo %}
                                <img src="{{ writer.writer_photo }}" class="img-responsive">
                            {% else %}
                                <h3>No image to display</h3>
                            {% endif %}
                        </a>
                    <h1>{{ writer.name }} <small>{{ writer.genre }}</small></h1>
                    <h2>{{ writer.nationality }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation"><a href="{% url 'books:writer_detail' writer.id %}">View All</a></li>
                <li role="presentation" class="active"><a href="{% url 'books:create_book' writer.id %}">Add New Song</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Song</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="album" value="{{ album }}">
                        {% include 'music/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

bookstore/books/templates/books/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

bookstore/books/templates/books/index.html
{% extends 'books/base.html' %}
{% block writer_active %}active{% endblock %}
{% block body %}

        <ul>
            {% for writer in all_writers %}
            <li>
            <div class="caption">
                <a href="{% url 'books:writer_detail' writer.id %}">
                <img src="{{ writer.writer_photo }}" style="width: 250px;">
                </a>
                <h2>{{ writer.name }}</h2>
                <h4>{{ writer.nationality }}</h4>
                <a href="{% url 'books:writer_detail' writer.id %}" class="btn btn-primary btn-sm"> View Details</a>
    <!--delete -->
                <form action="{% url 'books:writer-delete' writer.id %}" method="post" style="display: inline;">
                    {% csrf_token %}
                    <input type="hidden" name="writer_id" value="{{ writer.id }}"/>
                    <button type="submit" class="btn btn-default btn-sm">
                        <span class="glyphicon glyphicon-trash"></span>
                    </button>
                </form>
    <!--edit -->
                <a href="{% url 'books:writer-update' writer.id %}" class="btn btn-default btn-sm">
                        <span class="glyphicon glyphicon-edit"></span>
                </a>
            </div>
            </li>
            {% endfor %}
        </ul>

{% endblock %}

bookstore/books/templates/books/writer_detail.html
{% extends 'books/base.html' %}
{% block title %}{{ writer.name }} Details{% endblock %}
{% block body %}
<img src="{{ writer.writer_photo }}" style="width: 250px;">

<h1>Name: <small>{{writer.name}}</small></h1><h2>Genre:<small>{{ writer.genre }}</small></h2>
<h3>Nationality:<small>{{writer.nationality}}</small></h3>
<br>
<h4>Books:</h4>
    {% for book in writer.book_set.all %}
            <a href="{% url 'books:book_detail' book.id %}">{{ book.book_title }}</a>
            <br>
    {% endfor %}
{% endblock %}

bookstore/books/templates/books/writer_form.html
{% extends 'books/base.html' %}
{% block title %}Add a New Writer{% endblock %}
{% block writer_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'books/form_template.html' %}
                        <div class="form-group">

                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}